[versions]
kotlin = "2.4.20"
benManesVersions = "0.64.0"
liquibase = "5.0.4"
jooq = "3.21.8"
sqlite = "3.53.4.0"
h2 = "2.5.250"
junit = "6.1.3"
junitPlatform = "6.1.3"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
liquibase-core = { module = "org.liquibase:liquibase-core", version.ref = "liquibase" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
jooq-codegen = { module = "org.jooq:jooq-codegen", version.ref = "jooq" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "benManesVersions" }
